name: mpp-vg

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  k6:
    image: grafana/k6
    environment:
      BASE_URL: http://video-games:8080
    volumes:
      - target: /scripts
        source: ./perftests/dist
        type: bind
        read_only: true
    command: 'run -e TEST_FUNCTION=variousOps /scripts/index-test.js'
    extra_hosts:
      - video-games:192.168.1.194


volumes:
  pgdata: {}

