name: mpp-vg

services:
  frontend:
    image: ${REGISTRY_URI}mpp-videogames-frontend:${TAG:-latest}
    build:
      context: frontend
      dockerfile: frontend.Dockerfile
    ports:
      - target: 80
    networks:
      default:
        aliases:
          - frontend.mpp-vg.internal
  backend:
    image: ${REGISTRY_URI}mpp-videogames-backend:${TAG:-latest}
    build:
      context: backend
      dockerfile: backend.Dockerfile
    ports:
      - target: 8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db.mpp-vg.internal:5432/mydatabase
    depends_on:
      - db
    networks:
      default:
        aliases:
          - backend.mpp-vg.internal
  backendjs:
    image: ${REGISTRY_URI}mpp-videogames-backend-js:${TAG:-latest}
    build:
      context: backend-js
      dockerfile: backend-js.Dockerfile
    ports:
      - target: 5000
    volumes:
      - uploads:/backend-js/uploads
    networks:
      default:
        aliases:
          - backendjs.mpp-vg.internal
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - target: 5432
        published: 5432
    networks:
      default:
        aliases:
          - db.mpp-vg.internal
volumes:
  pgdata: {}
  uploads: {}

